### ISSUE TITLE
FATAL failed to fetch Master Machines: failed to load asset "Install Config": invalid "install-config.yaml" 

### ISSUE THREAD

**Issue by harkconnen** [openshift-metal3/dev-scripts#1137]
**Describe the bug**
I'm installing OCP4 following this info: "OpenShift 4 Bare Metal Install - User Provisioned Infrastructure (UPI)"
https://github.com/ryanhay/ocp4-metal-install

**To Reproduce**
At task: "Generate and host install files", step#5: run "~/openshift-install create manifests --dir ~/ocp-install"

**Expected/observed behavior**
create a manifest file for openshift, ...  but an error message says :"FATAL failed to fetch Master Machines: failed to load asset "Install Config": invalid "install-config.yaml" 
Reviewing the openshift_install.log file we can found this: 
time="2020-10-23T07:10:57-05:00" level=debug msg="OpenShift Installer 4.5.15"
time="2020-10-23T07:10:57-05:00" level=debug msg="Built from commit 9893a482f310ee72089872f1a4caea3dbec34f28"
time="2020-10-23T07:10:57-05:00" level=debug msg="Fetching Master Machines..."
time="2020-10-23T07:10:57-05:00" level=debug msg="Loading Master Machines..."
time="2020-10-23T07:10:57-05:00" level=debug msg="  Loading Cluster ID..."
time="2020-10-23T07:10:57-05:00" level=debug msg="    Loading Install Config..."
time="2020-10-23T07:10:57-05:00" level=debug msg="      Loading SSH Key..."
time="2020-10-23T07:10:57-05:00" level=debug msg="      Loading Base Domain..."
time="2020-10-23T07:10:57-05:00" level=debug msg="        Loading Platform..."
time="2020-10-23T07:10:57-05:00" level=debug msg="      Loading Cluster Name..."
time="2020-10-23T07:10:57-05:00" level=debug msg="        Loading Base Domain..."
time="2020-10-23T07:10:57-05:00" level=debug msg="        Loading Platform..."
time="2020-10-23T07:10:57-05:00" level=debug msg="      Loading Pull Secret..."
time="2020-10-23T07:10:57-05:00" level=debug msg="      Loading Platform..."
time="2020-10-23T07:10:57-05:00" level=fatal msg="failed to fetch Master Machines: failed to load asset \"Install Config\": invalid \"install-config.yaml\" file: pullSecret: Invalid value: \"b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAAB...............CAwQFBg==\": invalid character 'b' looking for beginning of value"

**Additional context**
the original version used in the lab guide is ocp 4.5.6.

Thanks in advance for your time.

**Comment by hardys** [comment]
>I'm installing OCP4 following this info: "OpenShift 4 Bare Metal Install - User Provisioned Infrastructure (UPI)"

Hi @harkconnen thanks for the report, but I don't think your issue is related to this repo - the scripts here are for developers working on [OpenShift Baremetal IPI](https://github.com/openshift/installer/blob/master/docs/user/metal/install_ipi.md) which uses [metal3](https://metal3.io/) internally for fully automated baremetal deployments.  That is not a UPI process such as you're attempting.

>https://github.com/ryanhay/ocp4-metal-install

If you're in agreement I'd suggest we close this and you can open an issue on that repo, but first I'd suggest checking the pullSecret in your install-config.yaml - the error indicates that is the problem, and it looks like you're passing a string with a single secret instead of the whole json string from https://cloud.redhat.com/openshift/install/pull-secret ?

**Comment by harkconnen** [comment]
Thanks @hardys!
it is solved, my error was to use "ssh-keygen" key instead of red hat pull-secret... (what a shame on me).
If you guys preferred to move or delete this entry, is ok to me. Thanks for the advice.

**Comment by harkconnen** [comment]
I should have used the Red Hat pull-secret key (https://cloud.redhat.com/openshift/install/pull-secret) instead of ssh-keygen's generated.
