### ISSUE TITLE
The path mentioned does not exist. source action fails

### ISSUE THREAD

**Issue by Stef1010** [openshift-metal3/dev-scripts#355]
https://github.com/openshift-metalkube/dev-scripts/blob/ecf60de2ea62593bb1613c5ee1af2a888ed3d261/assets/files/etc/kubernetes/manifests/mdns-publisher.yaml#L47

[core@master-1 ~]$ source /etc/kubernetes/static-pod-resources/clusterrc
-bash: /etc/kubernetes/static-pod-resources/clusterrc: No such file or directory
[core@master-1 ~]$ source /etc/kubernetes/static-pod-resources/mdns/clusterrc 
[core@master-1 ~]$

**Comment by karmab** [comment]
from the yaml file you indicate, this file is supposed to be created by the init container  clusterrc-generation but the corresponding file is indeed not there

**Comment by Stef1010** [comment]
ack thanks

**Comment by Stef1010** [comment]
Thanks for the quick response. Is this one  being deleted ? After deployment I do not see that file.

**Comment by karmab** [comment]
i dont think it should get deleted.
i believe that the issue is that /etc/kubernetes/static-pod-resources/kubeconfig doesnt seem to exist, so clusterrc doesnt get generated by the init container 
@celebdor thoughts ?

**Comment by cybertron** [comment]
I think this is because we're mounting /etc/kubernetes/static-pod-resources/mdns/ as /etc/kubernetes/static-pod-resources/ in the container. So on the host the file does not exist at the specified location, but when the container runs it will be there.

Looking at the masters in my local dev env I do see /etc/kubernetes/static-pod-resources/mdns/clusterrc so I think this is working as intended.

**Comment by russellb** [comment]
@cybertron should this be closed then?

**Comment by cybertron** [comment]
@russellb Yes, I think so.
