### ISSUE TITLE
Bootstrap fails due to bad MAC addresses if VMs are reused

### ISSUE THREAD

**Issue by dustinblack** [openshift-metal3/dev-scripts#460]
**Describe the bug**
Ironic will boot the VMs into the inspector image because the node MAC addresses are not recognized, leading to an overall bootstrap failure.

**To Reproduce**
We specifically reproduced this by taking snapshots of the VMs, then running `make clean`, which does not undefine the VMs because of the snaps. A subsequent deployment then attempts to reuse the existing VMs, but it also in the process redefines the MAC metadata for the deployment. Because the newly-defined MACs do not match the old VM MACs, the VMs are booted with the inspector image, and damage ensues.

The snapshots should not be a required ingredient of the reproducer -- You should simply be able to attempt a redeploy over existing VMs.

**Expected/observed behavior**
The scripts would optimally recognize that there are existing VMs and use their current MAC addresses for the deployment.

**Additional context**
As expected, the `Undefine overcloud vms` task fails during the `host_cleanup.sh` script when attempting the `make clean` in the environment that has the VM snaps.

**Comment by hardys** [comment]
I think this can be achieved by using only a subset of the scripts or make targets - it doesn't make sense to run the host cleanup (or setup) in the case where VMs already exist, but you can run e.g ocp_cleanup.sh then redeploy.

Can you perhaps share the exact steps you're using, then we can discuss a subset to achieve what you want?

That said, we've never supported VM snapshots, the idea is you either reuse the existing VMs as-is, or clean them completely and start from scratch (which shouldn't be too time-costly since we cache the OS images)

**Comment by hardys** [comment]
I'm going to close this since there's not been any reply to my question, and we don't expect to generally support snapshots which appear to be the root-cause of this problem.
