### ISSUE TITLE
Two IP addresses (DHCP)  allocated for Provisioning/External networks in the bootstrap node 

### ISSUE THREAD

**Issue by yboaron** [openshift-metal3/dev-scripts#512]
**Describe the bug**
Bootstrap node allocates two IP addresses (DHCP) instead of one for both Provisioning and External networks.

**To Reproduce**
Run deployment, ssh to bootstrap node before he's being deleted, and check 'ip -4 a'

**Expected/observed behavior**
a single IP address allocated for Baremetal/Provisioning networks.

**Additional context**
I 'tcpdumped' the  baremetal network at the host, and I can clearly see two DHCP requests for each network (with the same MAC address).
After looking deeply in bootstrap logs, It seems that the first DHCP request sent in initrd phase and the second one sent by NM.

**Comment by yboaron** [comment]
issue #494 is a side effect of this bug.
After two IPs were created, the IP address that was allocated at initrd phase (192.168.111.43 in [1]) is removed after DHCP LEASE timeout.
But the corresponding routing entry (i.e: 192.168.111.0/24 dev ens3 proto kernel scope link src 192.168.111.43 )is not deleted, and a result of that we can't communicate with hosts in the external subnet until this route is deleted manually.

So, if it takes to the bootstrap more than DHCP lease timeout to finish his part, we may stuck in the status described in issue #494  

[1]
[core@localhost ~]$ ip route 
default via 192.168.111.1 dev ens3 
default via 192.168.111.1 dev ens3 proto dhcp metric 100 
10.88.0.0/16 dev cni0 proto kernel scope link src 10.88.0.1 linkdown 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.26 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.27 metric 101 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.26 metric 101 
192.168.111.0/24 dev ens3 proto kernel scope link src 192.168.111.43 
192.168.111.0/24 dev ens3 proto kernel scope link src 192.168.111.44 metric 100 
192.168.111.0/24 dev ens3 proto kernel scope link src 192.168.111.43 metric 100 
192.168.111.0/24 dev ens3 proto kernel scope link src 192.168.111.2 metric 100 
[core@localhost ~]$

**Comment by thom311** [comment]
I don't have now a logfile at hand to confirm, but last time I looked at this, the following appeared to happen:

- in initrd, dhclient obtains a lease and configured an address of limited lifetime.

- in real-boot, NetworkManager is starting. When NetworkManager starts and the interface is already configured (with IP addresses), then one of 3 things can happen:

  1) the device is configured as unmanged, NM does nothing with the device.
  2) the device is managed and NetworkManager has  a connection profile that matches. If NM guesses that the profile was active previously, NetworkManager will take over the device non-destructively. That means, it does not remove IP addresses, but it will start doing DHCP on that device. NetworkManager logs then something about `sys-iface-state: 'assume'`. The purpose of this behavior is to facilitate restart of NetworkManager without loosing connectivity. It does not work well to hand over IP configuration from initrd to NetworkManager.
  3) NetworkManager does not think that it should take over the device. In this case, NetworkManager generates an in-memory profiles (named like the interface itself), and *pretends* that this profile is active. This is done to show that something is going on with the device. But NetworkManager will not touch the device in any way.

- In this case, NetworkManager did ii). It means, it starts doing DHCP, but the pre-existing IP addresses and routes are thought to be intentional configured and are preserved. NetworkManager actively configures the device, but these addresses are left.

- eventually, the lifetime of the address expires, and kernel removes the address. But kernel does not remove the route (because the route does not have a lifetime and does not obviously belong to the IP addresses). Afterwards, routing is broken due to wrong route.


The root problem is that the handover from initrd/dhclient to NetworkManager does not work and NetworkManager aquires a new lease and you end up with two IP addresses (instead of re-using the same IP address). This will be fixed by running NetworkManager also in initrd. NetworkManager knows how to pass over the data to itself in real-boot.

It's not clear to me how to fix the problem otherwise. Obviously, if you manually interact, you can just issue a `nmcli connection up` so that NetworkManager will purge the wrong IP addresses and start clean. But that is not general solution. I guess you could run `ip addr flush && ip route flush` before NetworkManager starts...

**Comment by schmaustech** [comment]
I have since moved my bootstrap node from a physical node to a virtual node and cannot reproduce this issue.

**Comment by yboaron** [comment]
I checked the two DHCP discover messages sent by the bootstrap node, first one in initrd phase and the second by NM. It seems that they have different 'client identifier', and that explains why the DHCP server allocates two different IPs for the same MAC.

[bootstrap_firstdhcp.txt](https://github.com/openshift-metal3/dev-scripts/files/3212747/bootstrap_firstdhcp.txt)
[bootstrap_second_dhcp.txt](https://github.com/openshift-metal3/dev-scripts/files/3212748/bootstrap_second_dhcp.txt)

**Comment by russellb** [comment]
Is there a bug tracking this getting fixed in RHCOS?  If not, let's open one.  Either way, let's link it here to track to resolution.

**Comment by yboaron** [comment]
@russellb Yes, they filed a bug on RHCOS JIRA for this issue, do you think we should file a bug also in RHCOS github?

**Comment by russellb** [comment]
> @russellb Yes, they filed a bug on RHCOS JIRA for this issue, do you think we should file a bug also in RHCOS github?

a downstream product bug is fine, I guess.  If they also track their work in some upstream location, then yeah it would be nice to have an upstream link we can reference here.

**Comment by yboaron** [comment]
@russellb  The RHCOS gitlab repo is internal

**Comment by hardys** [comment]
@yboaron  Does #616 close this?

**Comment by yboaron** [comment]
> @yboaron Does #616 close this?

@hardys - No, #616 update keepalived code to handle the case of more than one IP address is allocated per interface. 
We can close this bug when relevant bug (there's only downstream Jira for RHCOS) will be fixed in RHCOS

**Comment by hardys** [comment]
@yboaron any update on this?

**Comment by yboaron** [comment]
@hardys, Here's the latest status:
According to CoreOs guys, the bug fix (from FCOS) won't be included in RHCOS for 4.2 release.
For RHCOS 4.2, we have a workaround (in RHCOS) that flushes the first IP address, still, two IP addresses are allocated by DHCP, but only one of them is used (so we won't hit the extra route bug )

I think we should keep this issue in open status

**Comment by yboaron** [comment]
I verified that the problem was resolved in the latest RHCOS version (as reported by RHCOS guys).
The details of checked RHCOS version are at [1] 

And in [2] we can see that only a single IP address (192.168.111.52) is allocated for the bootstrap node.


[1] : 
[core@localhost ~]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux CoreOS"  
VERSION="42.80.20190827.1"              
VERSION_ID="4.2"                         
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 42.80.20190827.1 (Ootpa)"
ID="rhcos"                                                            
ID_LIKE="rhel fedora"                                                 
ANSI_COLOR="0;31"                                                     
HOME_URL="https://www.redhat.com/"                                    
BUG_REPORT_URL="https://bugzilla.redhat.com/"                         
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"                
REDHAT_BUGZILLA_PRODUCT_VERSION="4.2"                                 
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"                 
REDHAT_SUPPORT_PRODUCT_VERSION="4.2"                                  
OSTREE_VERSION=42.80.20190827.1                                       
[core@localhost ~]$ 
[2]  
[kni@dell-r630-006 dev-scripts]$ sudo virsh net-dhcp-leases  baremetal
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
 2019-09-09 11:15:23  00:18:06:a1:04:dd  ipv4      192.168.111.20/24         master-0        01:00:18:06:a1:04:dd
 2019-09-09 11:15:22  00:18:06:a1:04:e1  ipv4      192.168.111.21/24         master-1        01:00:18:06:a1:04:e1
 2019-09-09 11:15:24  00:18:06:a1:04:e5  ipv4      192.168.111.22/24         master-2        01:00:18:06:a1:04:e5
 2019-09-09 11:35:44  00:18:06:a1:04:e9  ipv4      192.168.111.23/24         worker-0        01:00:18:06:a1:04:e9
 2019-09-09 11:06:53  52:54:00:b6:f4:4a  ipv4      192.168.111.52/24         -               01:52:54:00:b6:f4:4a
