### ISSUE TITLE
2nd high-speed networking port needed for Ceph pods

### ISSUE THREAD

**Issue by bengland2** [openshift-metal3/dev-scripts#517]
**Describe the bug**

In a baremetal system with 2 high-speed NIC ports, metalkube I mean metal3 only assigns one of them an IP address.    This leads to Ceph only having access to 1 of them.   In a configuration with 4 NVM SSDs and 2 25-GbE ports, this cripples Ceph's ability to keep up with NVM devices (any other app using NVM storage might have this issue).  I'm relatively new to metal3 and CoreOS so if I overlooked something please let me know.

**To Reproduce**
Cloned from github metalkube/dev-scripts April 30, successful deployment twice.

common.sh:
    # External interface for routing traffic through the host
    # assuming this is the one that is connected to the outside world
    # 10 GbE.
    EXT_IF=${EXT_IF:-"em3"}
    # Provisioning interface used for PXE booting etc - 1 GbE
    PRO_IF=${PRO_IF:-"em1"}
    # Internal interface - 25-GbE
    INT_IF=${INT_IF:-"p7p1"}

**Expected/observed behavior**

Since metal3 is deploying the operating system, and the interfaces can't easily be changed after Kubernetes is running, I'd expect that network interface configuration should be specifiable in inputs to metal3.  Alternatives:
* bonding - allow mode 4 bonding of interfaces, which provides better HA and performance also.  Unlike the Ceph cluster network approach below, bonding mode 4 helps speed up read workloads.
* multus - allow pods to utilize > 1 interface (using macvlan plugin?)
* host networking - allow pods to access any and all host network interfaces

It seems like having the pods access the host network directly is problematic for security and multi-tenancy, but it would satisfy Ceph's immediate performance needs.  But even in this case, an IP still has to be assigned to the 2nd NIC port in some way in order for Ceph to use it.

**Additional context**

[Ceph network recommendations here](http://docs.ceph.com/docs/master/start/hardware-recommendations/#networks)

**Comment by jtaleric** [comment]
I was under the impression we were using both interfaces. However, I suspected a while ago that only a single interface was being used. Upon further investigations (literally today I was able to hook up a Mutable Grafana instance to Prometheus). I can clearly see only a single interface is being used by the platform. https://snapshot.raintank.io/dashboard/snapshot/PwcBlcjrnVaMcdlJEhmmskwldECmVc3m?refresh=10s&panelId=21&fullscreen&orgId=2

**Comment by dhellmann** [comment]
We've said that the "provisioning" network would be managed by the installation tools but any other networks needed to be set up to have persistent DHCP leases provided by some other system.

**Comment by jtaleric** [comment]
Hey @dhellmann from some emails I saw flying around, I was under the impression we had two interfaces to work with. One being the provisioning network, and one being the "public" aka API network. 

Is this not the case?

**Comment by dhellmann** [comment]
> Hey @dhellmann from some emails I saw flying around, I was under the impression we had two interfaces to work with. One being the provisioning network, and one being the "public" aka API network.
> 
> Is this not the case?

The NICs are there, but we're assuming DHCP provided by the environment for anything other than the private provisioning network.

**Comment by hardys** [comment]
> > Hey @dhellmann from some emails I saw flying around, I was under the impression we had two interfaces to work with. One being the provisioning network, and one being the "public" aka API network.
> > Is this not the case?
> 
> The NICs are there, but we're assuming DHCP provided by the environment for anything other than the private provisioning network.

IIRC the idea was that storage replication could perhaps happen on the same physical fabric as the provisioning network, but via either a static configuration on a separate subnet, or perhaps a dedicated vlan we can discover during introspection.

I don't think we can expect to have DHCP provide the separate subnet for this, due to the risk of collision with the ironic/provisioning DHCP, so it'll need to be a static configuration I think - I suspect having a vlan defined is likely to be the simplest approach, but we need to decide what will configure the interface to reach it (e.g should the install workflow do that, or can rook reasonably be expected to configure an interface for this?

**Comment by russellb** [comment]
As a general thing, we should rely on day 1 install configuration for as little as possible.  Consider a baremetal cluster that decides to install rook later.  How would that configuration work?  The same solution to that should apply here.  I feel the same way about the proposed bridge for use by VMs proposed in #282

**Comment by hardys** [comment]
We've agreed that all post-deploy network configuration will be taken care of the operators deploying the applications, so this should be handled via rook, and the kubevirt case will be handled via https://github.com/kubevirt/hyperconverged-cluster-operator.

As such I'll close this and we can follow up via issues to the respective operators.

Also, we're removing rook/kubevirt support from dev-scripts ref https://github.com/openshift-metal3/dev-scripts/pull/603 since they were only added to support demo work, and the eventual aim is to remove everything except the actual development environment setup from this repo.

**Comment by bengland2** [comment]
For now, the resolution I'm using (from Ben Schmaus) is to deploy openshift using the 2nd fast network port (e.g. 25-GbE NIC port 2), and have it use 25-GbE NIC port 1 for openshift management.  This ensures that IP addresses are assigned to both NIC ports.   Ceph can then reference these IP subnets in "public network" and "cluster network" parameters in Ceph configuration map (because Ceph containers uses host networking), and thereby get full network bandwidth out of the NIC on writes.   On reads, this does not solve the problem - only bonding/teaming can do that.   IMHO It is not reasonable to expect Ceph install scripting to manage NIC cards and assign IPs to them - Ceph is a TCP/IP application at present and does not know what else the systems are being used for.

**Comment by hardys** [comment]
@bengland2 thanks for the update - we still need to figure out what will handle the configuration of the second network, and how to deal with the multiple applications that want to use it (I'm assuming we only have two NICs, one for the ocp controlplane which is the "public" network, and another internal network that we're already using for provisioning of nodes via Ironic, and it seems is desired to provide the "cluster network" subnet for ceph?

Right now we don't have an IPAM solution for the internal/cluster network, so we only bring up that nic on the node where the baremetal-operator pod runs Ironic.  Ultimately I think we'll need a way to assign an IP to each node on the internal network (perhaps via the baremetal operator or cluster-api-provider-baremetal) so that we can then use some cluster-native approach like https://github.com/nmstate/kubernetes-nmstate to configure the secondary network.  As of right now all of that work is still TODO though.

**Comment by bengland2** [comment]
@hardys with the advent of NVM storage, the performance bottleneck for *any* distributed-storage application (Ceph, Kafka, etc) has shifted from the storage device to the network (for large I/O requests) and CPU (for small I/O requests).    Users will want the option to utilize all of our network resources to provide access to these very expensive and fast storage devices.

**Comment by hardys** [comment]
@bengland2 sure, AFAIK nobody has ever disputed the requirement, we just need to identify the appropriate integration point and find resources to implement the desired support for a secondary network, configured as a day-2 operation.  

Currently what we have integrated via BMO/dev-scripts is https://github.com/metal3-io/static-ip-manager-image and that's essentially a temporary hack to enable day-1 deployment of workers, it won't provide the necessary IPAM and persistent configuration you need to utilize the second NIC for internal storage traffic, and also that traffic should probably be isolated on a separate vlan (which is outside the scope of day-1 deployment since it's application specific configuration).

I'm still not sure we collectively have a precise answer for the integration work needed here, so we'll need to work together to define the future backlog/design appropriately.
