### ISSUE TITLE
When having multiple workers Installation should be complete when all the workers are up 

### ISSUE THREAD

**Issue by itzikb-redhat** [openshift-metal3/dev-scripts#542]
When the installation is complete not all the workers are up.
It would be helpful to make sure the installation is complete when all the workers are up.

**Comment by hardys** [comment]
Please try to be more specific - what are you seeing, what did you expect to see?

How are you testing?  Libvirt or baremetal?  How many workers?

We need more information to act on bug reports :)

Also note there is already logic in `11_register_hosts.sh` to wait for the default single worker on libvirt to become ready, but currently we can't wait on baremetal, or when multiple workers are used, because we're lacking automated machine-node association (which is already mentioned in the script).

**Comment by hardys** [comment]
Ok this is a known issue, work being tracked in #260 will ultimately enable us to wait for the masters, but the final solution will be to have kni-installer wait for them which is tracked via https://github.com/openshift-metal3/kni-installer/issues/46

**Comment by dhellmann** [comment]
Is this still an issue? I see references to #260, which is open, and openshift-metal3/kni-installer#46 which has merged.

**Comment by russellb** [comment]
If you configured a deployment with 3 workers, the install will not wait for all workers to be up successfully.  I feel like this is not actually a dev-scripts issue.  This is the behavior of any OpenShift cluster.  It waits on a functioning cluster, not on each specific deployed host necessarily.
