### ISSUE TITLE
Prometheus doesn't collect ironic data

### ISSUE THREAD

**Issue by honza** [openshift-metal3/dev-scripts#645]
The ironic exporter is installed in the ironic-image, and appears to be running correctly on the libvirt host. However, the Prometheus cluster isn't configured to scrape that data. There is no baremetal data present in the dashboard.

**Comment by ohadlevy** [comment]
could someone look into this sooner than later as it blocks the bare metal dashboard initiative? thanks.

**Comment by ohadlevy** [comment]
also, is there a design document (or just a link to the code) mentioning which data is available and how often is it being collected? thanks.

**Comment by hardys** [comment]
IMHO it doesn't really make sense to do this integration in dev-scripts, because we're in the process of moving from a hack which uses the host ironic via a proxy container to a fully cluster-managed ironic instance (which is what you really need to maintain long-term metrics on the cluster):

https://github.com/metal3-io/baremetal-operator/pull/212

The other pending part is https://github.com/metal3-io/baremetal-operator/pull/226 proposed by @
iurygregory  - perhaps he can confirm if by landing that we can use the ironic via the proxy container without dev-scripts testing (how has it been tested?)

**Comment by russellb** [comment]
I commented on the BMO PR.  I do'nt think that's the right place for it since it's OpenShift specific.  I'd suggest this is part of BMO integration with the machine-api-operator. Adding it there will be easy, but it's blocked on a number of things, but most notably finishing builds of a handful of openshift images (ironic, ironic-exporter, rhcos-downloader?).  It's also in the process of being rebased.

I would manually configure this (create the necessary ServiceMonitor manually) for dev purposes in the meantime.  It could be a couple more weeks before this is all ready.

**Comment by iurygregory** [comment]
Hey Everyone,

The `ironic-prometheus-exporter` is only able to collect data from real hardware. We have tested with our the QA if the metrics would be available in the directory and if we are able to request the stored data from the URL `http://<ironic-container-address>:5001/metrics`.

@russellb I've talked with @dhellmann about the place for the `ServiceMonitor` for the `ironic-prometheus-exporter`, initially we decided that would be under the `BMO` since it will deploy the `ironic-container` and it's where the `ironic-prometheus-exporter` is. I have no problem in push the PR in the machine-api-operator, mayybe we should have a quick meeting to decide wich path we should go?

@hardys tbh I don't know how we would test if the `ServiceMonitor` is working (in my mind we would need the full deployment and using openshift and we would be able to see the baremetal metrics there?)

@ohadlevy I will sent you the doc with the metrics that we have available now =)

**Comment by hardys** [comment]
> @hardys tbh I don't know how we would test if the `ServiceMonitor` is working (in my mind we would need the full deployment and using openshift and we would be able to see the baremetal metrics there?)

Exactly, I thought you may have tested with a full deployment via dev-scripts, and added the port to the temporary proxy container implemented via the baremetal-operator.

While it's true that the final integration of this running on-cluster is blocked by the items mentioned by @russellb I think that could be a viable short-term workaround for @honza, and also a way to de-risk any remaining gaps in the prometheus integration.

**Comment by hardys** [comment]
We're not longer consuming a version of ironic that contains the exporter component, so closing this issue as obsolete
