### ISSUE TITLE
4.3 deployment fails with Error: couldn't find key cache_url in ConfigMap openshift-machine-api/metal3-config

### ISSUE THREAD

**Issue by mcornea** [openshift-metal3/dev-scripts#905]
**Describe the bug**
IPv6 deployment fails with Error: couldn't find key cache_url in ConfigMap openshift-machine-api/metal3-config

**To Reproduce**
Depoloy 4.3.0-0.nightly-2020-01-21-205041-ipv6.5 with ipv6 baremetal network.

**Expected/observed behavior**

```shell
[kni@provisionhost-0 dev-scripts]$ oc describe -n openshift-machine-api pods/metal3-57cd4fd768-mttw6 | grep Error
      Reason:       CreateContainerConfigError
  Warning  Failed     17m (x12 over 19m)    kubelet, master-0.ocp-edge-cluster.qe.lab.redhat.com  Error: couldn't find key cache_url in ConfigMap openshift-machine-api/metal3-config

[kni@provisionhost-0 dev-scripts]$ oc -n openshift-machine-api get cm/metal3-config -o yaml
apiVersion: v1
data:
  rhcos_image_url: http://172.22.0.1/images/rhcos-43.81.202001142154.0-openstack.x86_64.qcow2.gz?sha256=6c35ff63be21640cf58ace6c81cb8d37f835772937702cc287af162c2a6732cc
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-25T04:49:32Z"
  name: metal3-config
  namespace: openshift-machine-api
  resourceVersion: "681"
  selfLink: /api/v1/namespaces/openshift-machine-api/configmaps/metal3-config
  uid: 78d65200-1347-495f-b923-22677ede480e
```

Since metal3 pod cannot come up worker nodes cannot be deployed and ingress routers are stuck in Pending state.

**Comment by hardys** [comment]
Thanks @mcornea - I think this is an issue for all 4.3 builds, and it's due to https://github.com/openshift-metal3/dev-scripts/pull/897 which depends on some recent (4.4 only) changes to the MAO and installer.

We'll have to decide if those changes get backported to 4.3 or if we should conditionally revert the removal of the config-map values for 4.3 builds in dev-scripts.

As a workaround you should be able to either revert that commit, or re-add the missing values into the metal3-config template:

https://github.com/openshift-metal3/dev-scripts/pull/897/commits/5c38184019ff5dcba45c337acd34af4a6df39de2#diff-970cc969e58a995c79016c4efd46dc2e

/cc @stbenjam

**Comment by stbenjam** [comment]
Would it make sense to maintain a 4.3 branch of dev-scripts? Rather than trying to support both in one branch.

**Comment by stbenjam** [comment]
This should be fixed now, by https://github.com/openshift-metal3/dev-scripts/pull/920

Please re-open if it's not working.

Thanks!
