### ISSUE TITLE
Nodes are not powered down on make clean and cause side effects

### ISSUE THREAD

**Issue by yrobla** [openshift-metal3/dev-scripts#906]
When i execute a `make clean` command, I expected that my nodes (masters/workers) are powered down. But that is not the case, while the bootstrap VM is powered down, losing all the services that were used by masters, such as coredns.
As a side effect, masters are still querying for addresses like api-int (resolved in the past by bootstrap vm), and this is causing a saturation (max queries reached) on the dns service of the installer host.

**Comment by dhellmann** [comment]
Is this problem still occurring?

**Comment by yrobla** [comment]
I think so yes, this was a problem when masters were not totally bootstrapped and vm was still there. But the issue as it was, is that i was expecting nodes to be powered down on make clean, and this is not happening.

**Comment by hardys** [comment]
This is expected as we've not got any destroy support for IPI baremetal in the installer yet ref https://github.com/openshift/installer/issues/2005

We could hack around it in a dev-scripts specific way (ipmitool etc), but I'm not sure it's worth it since we expect the end-user interface to be the installer.

**Comment by dhellmann** [comment]
When I run `make clean` my VMs are removed completely. Are you using VMs or real hardware?

**Comment by stbenjam** [comment]
We're tracking this as a wish list item to implement proper cluster destroy in the installer

/close
